### ISSUE TITLE
Link to https://oliver.st/flexible-pcb-connections/ is broken

### ISSUE THREAD

**Issue by cdluv** [oliveroliver/ffsc-generator#1]
Really intrigued about this project - I can see some great uses, so keen to see the examples, however the link is broken in the readme file

https://oliver.st/flexible-pcb-connections/ 

Returns 404 Not Found

**Comment by oliveroliver** [comment]
now fixed - and added examples to `readme.md`

**Comment by cdluv** [comment]
Thanks for the update.  Much appreciated!
